@startuml
:SearchByDateReservation;
:利用日選択(年月日入力、カレンダー入力もつけ、祝日とGW・お盆・年末年始の時期は選択できないようにする);
:選択した日付の施設・利用時間一覧(index);
if (休業日) then (yes)
:その施設の利用時間すべてをブランクにする;
:利用日選択に戻る;
stop
else if(休業日ではないが予約できない時間帯がある場合) then (yes)
:その時間帯をブランク(選択できないようにする);
else (nothing)
endif
:利用時間選択(複数選択可);

@enduml